import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from './store/ReduxProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const clashGrotesk = localFont({
  src: [
    {
      path: "./fonts/ClashGrotesk-Variable.ttf",
      style: "normal",
    },
  ],
  variable: "--font-clashGrotesk"
});
export const aeonik = localFont({
  src: [
    {
      path: "./fonts/Aeonik-Regular.ttf",
      style: "normal",
    },
  ],
  variable: "--font-aeonik"
});
export const plusJakarta = localFont({
  src: [
    {
      path: "./fonts/PlusJakartaSans.ttf",
      style: "normal",
    },
  ],
  variable: "--font-plusjakarta"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${clashGrotesk.variable} ${aeonik.variable}  ${plusJakarta.variable} antialiased`}
      >
        <ReduxProvider>
        {children}
          </ReduxProvider>
      </body>
    </html>
  );
}
